language: java
jdk: openjdk11

cache:
  directories:
    - $HOME/.m2

before_script:
  - psql -c 'create database topjava' -U postgres
  - psql -c 'create user "user"; grant all privileges on database topjava to "user"' -U postgres

branches:
  only:
    - master

env:
  - GRADUATION_ROOT=$TRAVIS_BUILD_DIR

notifications:
  email: false